# Generated by Django 3.0.5 on 2020-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200415_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='partner',
        ),
        migrations.AddField(
            model_name='entry',
            name='partner',
            field=models.ManyToManyField(to='main_app.Partner'),
        ),
    ]
