# Generated by Django 3.0.3 on 2020-04-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200416_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='health',
            name='feeling',
            field=models.CharField(choices=[('choice1', '&#128524;'), ('choice1', '&#128577;'), ('choice1', '&#128555;'), ('choice1', '&#128567;')], max_length=100, verbose_name='How do you feel today ?'),
        ),
    ]
