# Generated by Django 3.0.3 on 2020-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200416_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='date',
            new_name='dates',
        ),
    ]
