# Generated by Django 3.0.5 on 2020-04-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200416_1459'),
        ('main_app', '0014_auto_20200416_1419'),
    ]

    operations = [
    ]
