# Generated by Django 3.0.3 on 2020-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200416_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='dates',
            new_name='date',
        ),
    ]
