# Generated by Django 3.0.3 on 2020-04-16 02:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200415_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='health',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('choice1', 'I have Covid'), ('choice2', 'I recovered from'), ('choice3', 'I have fell sick'), ('choice4', 'Im not sick')], default=1, max_length=31),
            preserve_default=False,
        ),
    ]
