# Generated by Django 3.0.5 on 2020-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200416_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='location',
        ),
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
