# Generated by Django 3.0.3 on 2020-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200415_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='health',
            field=models.CharField(choices=[('choice1', 'I have Covid'), ('choice2', 'I recovered from'), ('choice3', 'I have fell sick'), ('choice4', 'Im not sick')], max_length=10),
        ),
    ]
