# Generated by Django 3.0.3 on 2020-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200416_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='feeling',
            field=models.ImageField(choices=[('choice1', 'static/images/happy.jpg'), ('choice2', 'https://imgur.com/71F3z7x.jpeg'), ('choice3', 'https://imgur.com/5C0AHib.jpeg'), ('choice4', 'https://imgur.com/iASVG4S.jpeg')], upload_to='', verbose_name='How do you feel today ?'),
        ),
        migrations.AlterField(
            model_name='health',
            name='health',
            field=models.CharField(choices=[('choice1', 'I’ve been dignoised with COVID-19 and would like to create a record of my whereabouts'), ('choice2', 'I’ve recoved from COVID-19, but would like to track my whereabouts'), ('choice3', 'I’ve not been tested for COVID-19, but feel sick and want to track my whereabouts'), ('choice4', 'I do not have COVID-19 but would like to track my whereabout')], max_length=100, verbose_name='Which option best describes your health status'),
        ),
    ]
