# Generated by Django 3.0.5 on 2020-04-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200416_2112'),
        ('main_app', '0014_auto_20200416_1419'),
    ]

    operations = [
    ]
