# Generated by Django 3.0.5 on 2020-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200417_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.CharField(default='friend', max_length=100),
            preserve_default=False,
        ),
    ]
