# Generated by Django 3.0.5 on 2020-04-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_partner_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='details',
        ),
    ]
